### ISSUE TITLE
Swept-angle based wing definition issues

### ISSUE THREAD

**Issue by svm420** [01010101lzy/B9-PWings-Fork#1] opened 2015-12-04 22:48 UTC
Hi I am getting a lot of log spam from the latest dll. The spam is the dimension of the wing be written over and over. Example

```
B9PW:Length Value changed to 16

(Filename: /home/builduser/buildslave/unity/build/artifacts/LinuxStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

B9PW:Width (root) Value changed to 2.875

(Filename: /home/builduser/buildslave/unity/build/artifacts/LinuxStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

B9PW:Width (tip) Value changed to 1.25

(Filename: /home/builduser/buildslave/unity/build/artifacts/LinuxStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

B9PW:Offset (tip) Value changed to 0.9999995
```

When switching to the new sweep angle mode I am unable to change the actual wing angle. Width length and thickness all work, but the newest sweep angle doesn't have any effect. I have logs set aside if you need the full thing, but as far as I could tell there are no actual exceptions just spam. Thanks! LMK if you need further testing

**Comment by svm420** [comment] 2015-12-04 22:59
Upon messing with it a bit more I started to have this spammed in my log 
`Scene::raycastAllShapes: The maximum distance must be greater than zero!`
After that started the window to modify the wings wouldn't return even when pressing J with the cursor over the wing. I had to unload the craft for the errors to stop.

**Comment by lynzrand** [comment] 2015-12-05 09:52
@svm420 
The first one is caused by the debugging method I used... Sorry for that, and I'm deleting those codes for a better experience.
I haven't met the second spam before, so please try to remake that spam and tell me how to have it occur. 
A new release fixing the first issue should be released in 30 minutes

**Comment by svm420** [comment] 2015-12-06 01:20
Still getting the debug spam. The wings still do not change shape with the new edge sweep controls. Logs here https://www.dropbox.com/s/alw2jra35o7pe3k/Player.log?dl=0 
Pictures in case that helps Notice the change to edge angles without the wing changing at all.
http://imgur.com/a/sY2KF

**Comment by lynzrand** [comment] 2015-12-06 14:55
It may need @HoneyFox to help me with this issue... I'l try.

---

@svm240 It seems you're not using the newest release...?

**Comment by svm420** [comment] 2015-12-06 19:05
I am sure I am, but just did another test pulling just the latest dll still get the spam and ~~edge sweep not working~~ fresh install just this mod and the squad folder. 

Seems I forgot to put a module manager in the folder last time doing so fixed the wings working with edge sweep, but I still get a ton of debug spam while the window is open. APologies for the misleading report last time. I will be more careful of my testing in the future. Great work by the way.

**Comment by svm420** [comment] 2015-12-06 19:25
As an idea for improvement if the sweep angle would read 0 when it currently reads ninety and increasing as you increase sweep handle. Currently it starts at 90 with a straight edge, and decrease as sweep increases. I would like it to start at 0 and increase with sweep and decrease as you sweep the opposite direction. Also if you add tip width to the new menu with sweep angle then you could fully customize the wings with just that menu. I do see you replaced that and offset tip in the sweep menu so I am not sure if you can have the 2 menus with a different number of sliders.

**Comment by lynzrand** [comment] 2015-12-07 09:38
Nice idea! So it would be decreasing sweep angle when sliding forward and increasing when sliding backwards, right?
For widths, I thought there would be a mess when you wanted to change the sweep angle after the tip width or offset, and the plugin would be unable to deal with what you _really_ want to change.(There might be two ways you wanted to change, keeping the offset or keeping tip width)

**Closed as completed** 2016-03-18 14:17 UTC
